name: Flutter analyze
on: [push, pull_request]

jobs:

  analyze:
    name: "Analyze flutter package"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - uses: subosito/flutter-action@v2.14.0
        with: 
          channel: "stable"
          cache: true

      - run: flutter pub get
      - run: flutter analyze
